backend:
  name: git-gateway
  branch: main
  local_backend: true          # for local dev with netlify-cms-proxy-server

media_folder: "src/images/uploads"     # where files are stored in repo
public_folder: "/images/uploads"       # how they are referenced by the site

publish_mode: editorial_workflow        # optional: adds review flow

collections:
  - name: "globals"
    label: "Globals"
    files:
      - name: "header"
        label: "Header"
        file: "src/_data/header.json"
        fields:
          - { label: "Logo", name: "logo", widget: "image", allow_multiple: false, media_folder: "src/images/uploads", public_folder: "/images/uploads" }
          - { label: "Logo Alt Text", name: "logo_alt", widget: "string", required: false }
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "href", widget: "string" }
      
      # NEW: editable footer
      - name: "footer"
        label: "Footer"
        file: "src/_data/footer.json"
        fields:
          - { label: "Main Line (address)", name: "text", widget: "string" }
          - { label: "Company No.", name: "company_no", widget: "string", required: false }
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Email", name: "email", widget: "string", required: false }
              - { label: "Phone", name: "phone", widget: "string", required: false }
          - label: "Social Links"
            name: "social"
            widget: "list"
            required: false
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "href", widget: "string" }
          - label: "Footer Links"
            name: "links"
            widget: "list"
            required: false
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "href", widget: "string" }
          - { label: "Copyright", name: "copyright", widget: "string", required: false, hint: "You can use {{ year }} here" }

  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "src/index.md"           # we'll convert homepage into Markdown + front matter
        fields:
          - {label: "Page Title", name: "title", widget: "string", default: "Zuricaf | Direct Ugandan Coffee & Climate-Smart Varieties"}
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Subtext", name: "subtext", widget: "string", required: false}
              - {label: "CTA Label", name: "cta_label", widget: "string", required: false}
              - {label: "CTA Anchor/URL", name: "cta_href", widget: "string", required: false}
              - {label: "Hero Image", name: "image", widget: "image", allow_multiple: false}
              - {label: "Hero Video (optional URL)", name: "video", widget: "string", required: false}
          - label: "Services"
            name: "services"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - {label: "Icon (lucide name)", name: "icon", widget: "string", required: false}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "desc", widget: "text"}
          - label: "Sustainability (rich text)"
            name: "sustainability"
            widget: "markdown"
          - label: "Liberica Section (rich text)"
            name: "liberica"
            widget: "markdown"
          - label: "Harvest Calendar"
            name: "calendar"
            widget: "list"
            fields:
              - {label: "Region", name: "region", widget: "string"}
              - {label: "Type", name: "type", widget: "string"}
              - {label: "Main Crop", name: "main", widget: "string"}
              - {label: "Fly Crop", name: "fly", widget: "string"}
          - label: "CTA Block"
            name: "cta"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Text", name: "text", widget: "string"}
              - label: "Buttons"
                name: "buttons"
                widget: "list"
                fields:
                  - {label: "Label", name: "label", widget: "string"}
                  - {label: "URL", name: "href", widget: "string"}

  - name: "assets"
    label: "Standalone Assets"
    folder: "src/content/assets"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body (optional)", name: "body", widget: "markdown", required: false}
      - {label: "Image/Video", name: "file", widget: "file"}
